#ifndef __USER_TASK_H
#define __USER_TASK_H

#include "SysConfig.h"

typedef enum
{
    USER_TASK_STATE_WAIT_START = 0,
    USER_TASK_STATE_PREPARE,
    USER_TASK_STATE_UNLOCK,
    USER_TASK_STATE_TAKEOFF,
    USER_TASK_STATE_HOVER,
    USER_TASK_STATE_TRACK_MODE,
    USER_TASK_STATE_ACQUIRE_CAR,
    USER_TASK_STATE_DROP_DESCEND,
    USER_TASK_STATE_DROP_DELAY,
    USER_TASK_STATE_DROP_RELEASE,
    USER_TASK_STATE_CLIMB_CRUISE,
    USER_TASK_STATE_CAR_LAND_DESCEND,
    USER_TASK_STATE_CAR_LOCK,
    USER_TASK_STATE_CAR_DWELL,
    USER_TASK_STATE_RETAKEOFF_MODE,
    USER_TASK_STATE_RETAKEOFF_UNLOCK,
    USER_TASK_STATE_RETAKEOFF_TAKEOFF,
    USER_TASK_STATE_RETAKEOFF_TRACK_MODE,
    USER_TASK_STATE_WAIT_CAR_A,
    USER_TASK_STATE_RETURN_H,
    USER_TASK_STATE_LAND_H,
    USER_TASK_STATE_LAND_FAILSAFE,
    USER_TASK_STATE_COMPLETE
} _user_task_state;

#define USER_TASK_TYPE_DROP       0U
#define USER_TASK_TYPE_DYNAMIC    1U

void UserTask_OneKeyCmd(void);
uint8_t UserTask_IsAutoControlActive(void);
uint8_t UserTask_GetState(void);
uint8_t UserTask_GetType(void);

#endif
